version: '3.1'

services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    ports:
      # HTTP port
      - 8123:8123
      # Native client port
      - 9000:9000
